#!/usr/bin/env python3
"""
Generate 400 person names across 8 different alphabet/writing systems.
Each alphabet gets 50 names, saved as separate files.
"""

import os

from utils import BASE_DIR

# 8 alphabets with 50 names each
names_by_alphabet = {
    "latin": [
        "John Smith",
        "Marie Dupont",
        "Carlos Rodriguez",
        "Anna Mueller",
        "Luca Ferrari",
        "Sophie Martin",
        "James Wilson",
        "Elena Rossi",
        "Hans Weber",
        "Isabella Garcia",
        "Michael Brown",
        "Claire Lefevre",
        "Pablo Sanchez",
        "Greta Schmidt",
        "Marco Antonio",
        "Emma Johnson",
        "Pierre Moreau",
        "Diego Torres",
        "Ingrid Hansen",
        "Alessandro Conti",
        "Oliver Davis",
        "Camille Bernard",
        "Miguel Hernandez",
        "Friedrich Wagner",
        "Matteo Romano",
        "Charlotte Anderson",
        "Jean Dubois",
        "Rafael Martinez",
        "Klaus Fischer",
        "Lorenzo Bianchi",
        "Amelia Thomas",
        "Nicolas Petit",
        "Fernando Lopez",
        "Stefan Schaefer",
        "Giuseppe Marino",
        "Mia Jackson",
        "Alexandre Roux",
        "Thomas Bernard",
        "Giulia Romano",
        "Lucas Silva",
        "María López",
        "Felix Bauer",
        "Sofia Andersen",
        "Diego Morales",
        "Elena Popovic",
        "Marco Silva",
        "Hannah Fischer",
        "Carlos Mendoza",
        "Amélie Laurent",
        "Nikolaj Jensen"
    ],
    "cyrillic": [
        "Александр Петров",
        "Мария Иванова",
        "Дмитрий Сидоров",
        "Анна Смирнова",
        "Сергей Кузнецов",
        "Елена Попова",
        "Андрей Васильев",
        "Ольга Николаева",
        "Максим Соколов",
        "Наталья Михайлова",
        "Иван Федоров",
        "Татьяна Новиков",
        "Николай Волков",
        "Ирина Александрова",
        "Владимир Лебедев",
        "Светлана Козлов",
        "Павел Семенов",
        "Екатерина Егорова",
        "Алексей Поляков",
        "Юлия Соловьев",
        "Роман Волков",
        "Виктория Павлова",
        "Евгений Степанов",
        "Анастасия Николаев",
        "Кирилл Орлов",
        "Дарья Андреева",
        "Илья Макаров",
        "Елена Захаров",
        "Михаил Бровко",
        "Оксана Краснова",
        "Григорий Леонидов",
        "Валентина Егоров",
        "Виталий Григоров",
        "Тамара Михайловна",
        "Борис Фёдоров",
        "Людмила Петровна",
        "Константин Яковлев",
        "Нина Сергеевна",
        "Вадим Иванов",
        "Галина Кузьмина",
        "Олег Тихонов",
        "Маргарита Белова",
        "Артём Козлов",
        "Вера Смирнова",
        "Георгий Морозов",
        "Зинаида Васильева",
        "Степан Романов",
        "Лариса Кудрявцева",
        "Фёдор Обухов",
        "Раиса Гусева"
    ],
    "chinese": [
        "王小明",
        "李娜",
        "张伟",
        "刘洋",
        "陈静",
        "杨帆",
        "赵磊",
        "黄丽",
        "周涛",
        "吴欣",
        "徐杰",
        "孙蕾",
        "马超",
        "朱婷",
        "胡军",
        "郭敏",
        "林峰",
        "何琳",
        "高飞",
        "罗芳",
        "梁勇",
        "宋佳",
        "郑浩",
        "谢蕾",
        "韩冰",
        "唐文",
        "冯鑫",
        "曹鹏",
        "邓丽",
        "彭涛",
        "曾洁",
        "卢凯",
        "蔡琴",
        "贾玲",
        "丁强",
        "魏然",
        "范伟",
        "潘艳",
        "袁朗",
        "蒋欣",
        "苏晴",
        "蔡明",
        "贾旭",
        "丁瑶",
        "魏晨",
        "叶凡",
        "沈腾",
        "韩红",
        "崔伟",
        "姚晨"
    ],
    "japanese": [
        "田中太郎",
        "佐藤美咲",
        "鈴木健一",
        "高橋さくら",
        "伊藤誠",
        "山本愛",
        "中村大輔",
        "小林梨花",
        "松井佑樹",
        "井上麻衣",
        "木村拓海",
        "林あおい",
        "清水直樹",
        "橋本優子",
        "石川亮",
        "山口真由美",
        "渡辺学",
        "森カレン",
        "池田陸",
        "吉田ひかり",
        "山田浩二",
        "スコトナ",
        "青木悠太",
        "東徹",
        "加藤みどり",
        "佐々木遼",
        "近藤七海",
        "岡田龍一",
        "中島果歩",
        "村上怜",
        "堀内遥",
        "内田葵",
        "原優介",
        "片岡彩",
        "藤田泰斗",
        "森田陽向",
        "後藤乃愛",
        "阿部聖",
        "市川陽向",
        "松田萌",
        "岡本峻",
        "久保美咲",
        "前田悠羽",
        "福田暖",
        "坂本樹",
        "塚田心",
        "池岡太陽",
        "鈴木百花",
        "竹内空",
        "小川宙"
    ],
    "arabic": [
        "أحمد محمد",
        "فاطمة علي",
        "محمد حسن",
        "عائشة إبراهيم",
        "علي محمود",
        "مريم أحمد",
        "خالد عمر",
        "نورة سعيد",
        "ممدوح رشيد",
        "ليلى كريم",
        "يوسف عباس",
        "هدى فاروق",
        "عمر ناصر",
        "رنا خطاب",
        "سامي حمدي",
        "دانة صلاح",
        "حسام بدوي",
        "أمل طه",
        "تامر جودة",
        "سلمى مراد",
        "ماجد شريف",
        "تسنيم رؤوف",
        "رائد لطفي",
        "غادة حلمي",
        "كريم أنور",
        "رانيا صبري",
        "أسامة جمعة",
        "لميس عبد",
        "والد مختار",
        "بهية شوقي",
        "زياد لطفي",
        "مها طه",
        "عادل حسني",
        "سحر رمضان",
        "فارس نبيل",
        "جنى مختار",
        "باسل عزت",
        "إيمان صبحي",
        "تركي ماجد",
        "هند فالج",
        "خالد السعيد",
        "نوال العتيبي",
        "فهد الدوسري",
        "ريم القحطاني",
        "سلطان الغامدي",
        "منال الشهراني",
        "بدر المطيري",
        "دانة العنزي",
        "فيصل الرشيدي",
        "عائشة السبيعي"
    ],
    "devanagari": [
        "राम सिंह",
        "सीता पटेल",
        "मोहन दास",
        "कमिनी शर्मा",
        "सुरेश कुमार",
        "रीता अग्रवाल",
        "विजय मेहता",
        "सुनीता जोशी",
        "अनिल चौहान",
        "पूजा गुप्ता",
        "राजेश वर्मा",
        "नेहा सक्सेना",
        "अमित ठाकुर",
        "दिव्या राजपूत",
        "संजय पटेल",
        "कविता सिंह",
        "गणेश जोशी",
        "मीरा देशमुख",
        "प्रकाश बर्मन",
        "अंजलि सक्सेना",
        "विनोद कुलकर्णी",
        "स्वति पवार",
        "मधुकर शिंदे",
        "संध्या नाईक",
        "राहुल जाधव",
        "प्रिया भट्ट",
        "सचिन पवार",
        "रेखा कुलकर्णी",
        "नितिन शिंदे",
        "उर्मिला नाईक",
        "अशोक धांडे",
        "माधुरी घोसल",
        "विक्रान्त मोरे",
        "सविता काले",
        "आदित्य कदम",
        "प्रियांका सुतार",
        "मनिष जाधव",
        "श्वेता पवार",
        "रोहित शिंदे",
        "निशा कुलकर्णी",
        "अमोल वाघ",
        "प्रिया देशाई",
        "सुरेश भोसले",
        "रेखा पवार",
        "कुणाल जाधव",
        "अपूर्व देशमुख",
        "इशांत कपूर",
        "दीया मेहता",
        "वेदांत राठौड़",
        "अनanya तिवारी"
    ],
    "korean": [
        "김민수",
        "이서연",
        "박지훈",
        "최유나",
        "정현우",
        "강혜진",
        "장도윤",
        "임소연",
        "권태현",
        "한지우",
        "유서윤",
        "충민호",
        "서지안",
        "홍유나",
        "신현우",
        "윤서연",
        "조태현",
        "강지우",
        "남유나",
        "민현우",
        "장서연",
        "오태현",
        "문지우",
        "조유나",
        "신서아",
        "한서연",
        "임태현",
        "권지우",
        "한유나",
        "김서연",
        "이태현",
        "박지우",
        "최서아",
        "정유라",
        "강민호",
        "정도윤",
        "임하윤",
        "권서현",
        "한민우",
        "유지훈",
        "박서아",
        "김태현",
        "최민호",
        "정지우",
        "강유나",
        "장서아",
        "임태현",
        "권지현",
        "한소연",
        "서민호"
    ],
    "nordic": [
        "Jørgen Hansen",
        "Åsa Lindström",
        "Björn Eriksen",
        "Ingrid Nilsen",
        "Søren Andersen",
        "Freya Jørgensen",
        "Magnus Østergaard",
        "Astrid Bjørnson",
        "Lars Kristiansen",
        "Sigrid Halvorsen",
        "Henrik Møller",
        "Elsa Strøm",
        "Per Nilsen",
        "Karin Jepsen",
        "Torben Sørensen",
        "Hilda Fjeld",
        "Espen Vang",
        "Maja Solberg",
        "Trond Birkeland",
        "Solveig Næss",
        "Kristian Løken",
        "Berit Stenberg",
        "Gunnar Sæther",
        "Tone Fjell",
        "Øyvind Hagen",
        "Asta Holm",
        "Stian Rød",
        "Liv Nordskog",
        "Bjørn Vik",
        "Kari Svendsen",
        "Finn Ødegård",
        "Inger Mørk",
        "Erik Støle",
        "Hannah Berg",
        "Nils Strøm",
        "Ragna Solheim",
        "Torbjørn Dahl",
        "Ylva Lund",
        "Asbjørn Fjellstad",
        "Sigurd Nordskog",
        "Helga Vinje",
        "Gustav Håkonsen",
        "Dagmar Eikeland",
        "Ragnar Solstad",
        "Birgitta Næss",
        "Leif Strand",
        "Moa Fjellestad",
        "Knut Øverland",
        "Signe Birkeland",
        "Harald Stang"
    ]
}

def save_names():
    """Save names to individual files and a master JSON file."""
    
    # Create the Generator directory if it doesn't exist
    os.makedirs(BASE_DIR, exist_ok=True)
    
    # Save each alphabet's names to a separate file
    for alphabet, names in names_by_alphabet.items():
        filepath = os.path.join(BASE_DIR, f"{alphabet}_names.txt")
        with open(filepath, 'w', encoding='utf-8') as f:
            for name in names:
                f.write(name + '\n')
        print(f"Saved {len(names)} {alphabet} names to {filepath}")
    
    # Save master JSON file
    import json

    json_path = os.path.join(BASE_DIR, "all_names.json")
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(names_by_alphabet, f, ensure_ascii=False, indent=2)
    print(f"\nSaved master list to {json_path}")
    
    # Print summary
    total = sum(len(names) for names in names_by_alphabet.values())
    print(f"\nTotal names generated: {total}")
    print(f"Alphabets: {', '.join(names_by_alphabet.keys())}")

if __name__ == "__main__":
    save_names()
    print("\nDone! Files created in Generator folder.")