services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.json:/etc/caddy/Caddyfile.json
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddy/Caddyfile.json
    networks:
      - app-network

  frontend:
    image: concos-frontend:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    image: concos-backend:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge