#!/usr/bin/env python3
"""Keycloak Setup Script for ConciergeOS.

Provisions realms, users, roles, and client configuration for ConciergeOS.
Usage: python keycloak_setup.py [keycloak_host] [keycloak_port]
Example: python keycloak_setup.py localhost 8080
"""

import argparse
import os
import sys

import requests
import yaml

from settings import settings


# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------

REALMS = ["testing", "production"]
CLIENT_ID = settings.OIDC_CLIENT_ID

# Derived from APP_DOMAIN - no hardcoded URLs
APP_DOMAIN = settings.APP_DOMAIN  # e.g., "https://out-customer.com"
OIDC_MAIN_REDIRECT_URI = f"{APP_DOMAIN}/oauth2/callback"
POST_LOGOUT_URI = f"{APP_DOMAIN}/"
LOCAL_REDIRECT_URI = "http://localhost:*/*"
LOCAL_WEB_ORIGIN = "http://localhost:*"
DOMAIN_WILD_CARD = f"{APP_DOMAIN}/*"
# Actual secret generated by Keycloak (updated during client creation)
_actual_client_secret = ""

# ------------------------------------------------------------------
# Role Definitions (loaded from rbac_routes.yaml)
# ------------------------------------------------------------------


def _load_roles_from_mapping() -> dict[str, str]:
    """Load role definitions from the RBAC mapping YAML file.

    Reads 'rbac_routes.yaml' and extracts the unique role names, deriving a
    human-readable description from each entry's *message* field.

    Returns
    -------
    dict[str, str]
        {role_name: description} suitable for Keycloak role creation.

    Notes
    -----
    Tries the following locations in order:
    1. MAPPING_FILE environment variable (set by settings.MAPPING_FILE)
    2. rbac_routes.yaml relative to this script's directory (local dev)
    """
    # Try the configured path first (works inside Docker containers)
    mapping_file = settings.MAPPING_FILE
    if not os.path.exists(mapping_file):
        # Fallback: look for rbac_routes.yaml next to this script (local dev)
        script_dir = os.path.dirname(os.path.abspath(__file__))
        fallback = os.path.join(script_dir, "rbac_routes.yaml")
        if os.path.exists(fallback):
            mapping_file = fallback
        else:
            raise FileNotFoundError(
                f"RBAC mapping file not found. Searched:\n"
                f"  1. {settings.MAPPING_FILE} (MAPPING_FILE env var)\n"
                f"  2. {fallback} (next to this script)\n"
                "Set MAPPING_FILE to point to rbac_routes.yaml."
            )

    with open(mapping_file, "r") as f:
        data = yaml.safe_load(f) or []

    roles: dict[str, str] = {}
    for entry in data:
        role_name = entry.get("role", "")
        if not role_name:
            continue

        # Derive a clean description from the YAML's 'message' field.
        # Example input : "Access denied: /settings requires the settings:view role."
        # Example output: "/settings requires settings:view"
        msg = entry.get("message", f"Role: {role_name}")
        description = (
            msg.replace("Access denied: ", "")
               .replace(" role.", "")
               .replace(" requires the ", " requires ")
        )
        roles[role_name] = description

    return roles


# Roles are loaded from rbac_routes.yaml — single source of truth.
ROLES = _load_roles_from_mapping()


# Composite role that inherits all granular roles defined in the mapping file.
# Updated dynamically so new roles in rbac_routes.yaml are automatically included.
def _get_composite_roles() -> dict[str, list[str]]:
    return {
        "full-access": list(ROLES.keys()),
    }


COMPOSITE_ROLES = _get_composite_roles()

USERS = {
    "user1": {
        "password": "password1",
        "roles": ["reservations:view", "guest-search:view"],
    },
    "user2": {
        "password": "password2",
        "roles": ["full-access"],
    },
}


def get_base_url(host: str, port: int) -> str:
    return f"http://{host}:{port}/auth"


def authenticate(base_url: str, username: str, password: str) -> str:
    """Authenticate as admin to the master realm and return access token."""
    print("[1/8] Authenticating as admin...")
    resp = requests.post(
        f"{base_url}/realms/master/protocol/openid-connect/token",
        data={
            "grant_type": "password",
            "client_id": "admin-cli",
            "username": username,
            "password": password,
        },
    )
    resp.raise_for_status()
    token = resp.json().get("access_token")
    if not token:
        print("ERROR: Failed to authenticate to Keycloak admin.")
        sys.exit(1)
    print("  ✓ Authenticated\n")
    return token


def api_request(
    method: str,
    url: str,
    token: str,
    payload: dict | list | None = None,
) -> requests.Response:
    """Make an API request to Keycloak admin API."""
    return requests.request(
        method,
        url,
        json=payload or {},
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
        },
    )


# ------------------------------------------------------------------
# 2. Create Realms
# ------------------------------------------------------------------


def create_realms(base_url: str, token: str) -> None:
    """Create realms: testing, production.

    Enables admin events and user events on each realm so that the
    role-sync service can poll the /admin/realms/{realm}/events endpoint.
    """
    print("[2/8] Creating realms...")
    headers = {"Authorization": f"Bearer {token}"}
    for realm in REALMS:
        resp = requests.get(
            f"{base_url}/admin/realms/{realm}",
            headers=headers,
        )
        if resp.status_code == 200:
            print(f"  ⏭ Realm {realm} already exists, ensuring events enabled")
            # Ensure events are enabled on existing realms
            _ensure_events_enabled(base_url, token, realm)
            continue
        resp = api_request("POST", f"{base_url}/admin/realms", token, {
            "realm": realm,
            "enabled": True,
            "adminEventsEnabled": True,
            "eventsEnabled": True,
            "eventsExpiration": 43200,  # 12 hours
        })
        resp.raise_for_status()
        print(f"  ✓ Realm {realm} created (events enabled)")
    print()


def _ensure_events_enabled(base_url: str, token: str, realm: str) -> None:
    """Enable admin and user events on an existing realm.

    Keycloak 26 requires a full PUT (not PATCH) to update realm config.
    """
    headers = {"Authorization": f"Bearer {token}"}
    realm_url = f"{base_url}/admin/realms/{realm}"

    # Read current realm config
    resp = requests.get(realm_url, headers=headers)
    resp.raise_for_status()
    config = resp.json()

    admin_events = config.get("adminEventsEnabled", False)
    user_events = config.get("eventsEnabled", False)

    if admin_events and user_events:
        return  # Already enabled

    # Merge event settings into full config
    config["adminEventsEnabled"] = True
    config["eventsEnabled"] = True
    config.setdefault("eventsExpiration", 43200)

    # PUT full config back (Keycloak 26 does not support PATCH for realms)
    resp = requests.put(realm_url, headers=headers, json=config)
    resp.raise_for_status()
    print(f"    ✓ Events enabled for {realm}")


# ------------------------------------------------------------------
# 3. Create Roles
# ------------------------------------------------------------------


def create_role(base_url: str, token: str, realm: str, role_name: str, description: str = "") -> str:
    """Create a realm role. Returns the role name (Keycloak roles are identified by name)."""
    # Check if role exists
    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/roles/{role_name}",
        headers={"Authorization": f"Bearer {token}"},
    )
    if resp.status_code == 200:
        print(f"    ⏭ Role {role_name} already exists")
        return role_name

    resp = api_request(
        "POST",
        f"{base_url}/admin/realms/{realm}/roles",
        token,
        {
            "name": role_name,
            "description": description,
        },
    )
    if resp.status_code in (201, 204):
        print(f"    ✓ Role {role_name} created")
    else:
        print(f"    ⚠ Failed to create role {role_name}: {resp.status_code} {resp.text}")
    return role_name


def create_composite_role(
    base_url: str,
    token: str,
    realm: str,
    role_name: str,
    composite_role_names: list[str],
) -> str:
    """Create a composite role that inherits from the given composite roles."""
    # First create the role itself
    create_role(base_url, token, realm, role_name, f"Composite role: {', '.join(composite_role_names)}")

    # Get the composite role IDs
    composite_role_ids = []
    for comp_name in composite_role_names:
        resp = requests.get(
            f"{base_url}/admin/realms/{realm}/roles/{comp_name}",
            headers={"Authorization": f"Bearer {token}"},
        )
        if resp.status_code == 200:
            composite_role_ids.append(resp.json().get("id"))

    # Set composites
    if composite_role_ids:
        resp = api_request(
            "PUT",
            f"{base_url}/admin/realms/{realm}/roles/{role_name}/composites",
            token,
            composite_role_ids,
        )
        # PUT returns 204 No Content on success
        if resp.status_code in (200, 204):
            print(f"    ✓ Composite role {role_name} configured with {len(composite_role_ids)} sub-roles")
        else:
            print(f"    ⚠ Failed to configure composites for {role_name}: {resp.status_code}")

    return role_name


def create_all_roles(base_url: str, token: str) -> dict[str, dict[str, str]]:
    """Create roles in all realms. Returns {realm: {role_name: role_data}}."""
    print("[3/8] Creating roles in realms...")
    role_data: dict[str, dict[str, str]] = {}

    for realm in REALMS:
        print(f"  Realm: {realm}")
        role_data[realm] = {}

        # Create granular roles
        for role_name, description in ROLES.items():
            role_data[realm][role_name] = create_role(
                base_url, token, realm, role_name, description
            )

        # Create composite roles
        for composite_name, sub_roles in COMPOSITE_ROLES.items():
            role_data[realm][composite_name] = create_composite_role(
                base_url, token, realm, composite_name, sub_roles
            )

    print()
    return role_data


# ------------------------------------------------------------------
# 4. Create Users
# ------------------------------------------------------------------


def create_user(base_url: str, token: str, realm: str, username: str, password: str) -> str:
    """Create a user in a realm. Returns the user ID.

    Keycloak blocks password grant for users with pending required actions
    (e.g., UPDATE_PASSWORD, VERIFY_EMAIL) with "Account is not fully set up".
    We set firstName/lastName and clear requiredActions to avoid this.
    """
    # Check if user exists
    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/users",
        params={"username": username, "max": 1},
        headers={"Authorization": f"Bearer {token}"},
    )
    resp.raise_for_status()

    if resp.json():
        print(f"    ⏭ User {username} already exists")
        user_id = resp.json()[0]["id"]
        # Ensure existing users also have required actions cleared
        _clear_required_actions(base_url, token, realm, user_id)
        return user_id

    resp = api_request(
        "POST",
        f"{base_url}/admin/realms/{realm}/users",
        token,
        {
            "username": username,
            "firstName": username,
            "lastName": "User",
            "enabled": True,
            "email": f"{username}@conciergeos.local",
            "credentials": [
                {
                    "type": "password",
                    "value": password,
                    "temporary": False,
                }
            ],
            "emailVerified": True,
            "requiredActions": [],
        },
    )
    resp.raise_for_status()

    # Extract user ID from Location header (HTTP 201 returns location)
    user_id = resp.headers.get("Location", "").split("/")[-1]
    if not user_id:
        # Fallback: query by username again
        resp = requests.get(
            f"{base_url}/admin/realms/{realm}/users",
            params={"username": username, "max": 1},
            headers={"Authorization": f"Bearer {token}"},
        )
        resp.raise_for_status()
        user_id = resp.json()[0]["id"]

    # Clear any required actions that Keycloak may have added
    _clear_required_actions(base_url, token, realm, user_id)

    print(f"    ✓ User {username} created")
    return user_id


def _clear_required_actions(base_url: str, token: str, realm: str, user_id: str) -> None:
    """Clear required actions on a user so password grant authentication works.

    Keycloak blocks password grant for users with pending required actions
    (e.g., UPDATE_PASSWORD, VERIFY_EMAIL) with "Account is not fully set up".
    We fetch the user, clear requiredActions, and PUT back.
    """
    headers = {"Authorization": f"Bearer {token}"}

    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/users/{user_id}",
        headers=headers,
    )
    resp.raise_for_status()
    user_data = resp.json()
    user_data["requiredActions"] = []

    resp = requests.put(
        f"{base_url}/admin/realms/{realm}/users/{user_id}",
        headers=headers,
        json=user_data,
    )
    resp.raise_for_status()


def create_all_users(base_url: str, token: str) -> dict[str, dict[str, str]]:
    """Create users in all realms. Returns {realm: {username: user_id}}."""
    print("[4/8] Creating users in realms...")
    user_ids: dict[str, dict[str, str]] = {}

    for realm in REALMS:
        print(f"  Realm: {realm}")
        user_ids[realm] = {}
        for username, config in USERS.items():
            user_ids[realm][username] = create_user(
                base_url, token, realm, username, config["password"]
            )
    print()
    return user_ids


# ------------------------------------------------------------------
# 5. Assign Users to Roles
# ------------------------------------------------------------------


def assign_user_to_roles(
    base_url: str,
    token: str,
    realm: str,
    user_id: str,
    role_names: list[str],
    username: str,
) -> None:
    """Assign a user to realm roles."""
    if not user_id:
        print(f"    ⚠ Skipping {username} (missing user ID)")
        return

    # Get all roles with their IDs and realm_access structure
    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/roles",
        headers={"Authorization": f"Bearer {token}"},
    )
    resp.raise_for_status()
    all_roles = {r["name"]: r for r in resp.json()}

    # Check existing role mappings
    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/users/{user_id}/role-mappings/realm",
        headers={"Authorization": f"Bearer {token}"},
    )
    resp.raise_for_status()
    existing_roles = {r["name"] for r in resp.json()}

    # Assign missing roles
    roles_payload = []
    for role_name in role_names:
        if role_name in existing_roles:
            print(f"    ⏭ {username} already has {role_name}")
            continue
        if role_name in all_roles:
            roles_payload.append({
                "id": all_roles[role_name]["id"],
                "name": role_name,
            })

    if roles_payload:
        resp = api_request(
            "POST",
            f"{base_url}/admin/realms/{realm}/users/{user_id}/role-mappings/realm",
            token,
            roles_payload,
        )
        if resp.status_code in (200, 204, 201):
            role_list = ", ".join(r["name"] for r in roles_payload)
            print(f"    ✓ {username} → {role_list}")
        else:
            print(f"    ⚠ Could not assign roles to {username}: {resp.status_code}")


def assign_all_users_to_roles(
    base_url: str,
    token: str,
    user_ids: dict[str, dict[str, str]],
    role_data: dict[str, dict[str, str]],
) -> None:
    """Assign all users to their respective roles in all realms."""
    print("[5/8] Assigning users to roles...")

    for realm in REALMS:
        print(f"  Realm: {realm}")
        for username, config in USERS.items():
            assign_user_to_roles(
                base_url,
                token,
                realm,
                user_ids[realm][username],
                config["roles"],
                username,
            )
    print()


# ------------------------------------------------------------------
# 6. Create Client
# ------------------------------------------------------------------


def create_client(base_url: str, token: str, realm: str) -> str:
    """Create the conciergeos client in a realm. Returns the client UUID.

    Keycloak 26 always generates a random secret. After creation, the actual
    secret is stored in _actual_client_secret and printed to stdout so the
    caller can set the OAUTH2_PROXY_CLIENT_SECRET environment variable.
    """
    global _actual_client_secret
    print(f"  Creating client: {CLIENT_ID} in {realm}...")

    # Check if client exists
    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/clients",
        headers={"Authorization": f"Bearer {token}"},
    )
    resp.raise_for_status()
    clients = resp.json()
    match = [c for c in clients if c["clientId"] == CLIENT_ID]

    if match:
        client_uuid = match[0]["id"]
        print(f"    ⏭ Client {CLIENT_ID} already exists in {realm}, will update secret...")
    else:
        resp = api_request(
            "POST",
            f"{base_url}/admin/realms/{realm}/clients",
            token,
            {
                "clientId": CLIENT_ID,
                "enabled": True,
                "publicClient": False,
                "standardFlowEnabled": True,
                "implicitFlowEnabled": False,
                "directAccessGrantsEnabled": True,
                "serviceAccountsEnabled": False,
                "redirectUris": [
                    OIDC_MAIN_REDIRECT_URI,
                    DOMAIN_WILD_CARD,
                    LOCAL_REDIRECT_URI,
                ],
                "webOrigins": [
                    APP_DOMAIN,
                    LOCAL_WEB_ORIGIN,
                ],
                # postLogoutRedirectUris is NOT a top-level field in Keycloak 26's
                # ClientRepresentation - it's stored as a semicolon-separated attribute
                # (see OIDCConfigAttributes.POST_LOGOUT_REDIRECT_URIS = "post.logout.redirect.uris")
                "attributes": {
                    "pkce.code.challenge.method": "S256",
                    "post.logout.redirect.uris": "##".join([
                        POST_LOGOUT_URI,
                        DOMAIN_WILD_CARD,
                        LOCAL_REDIRECT_URI,
                    ]),
                },
            },
        )
        resp.raise_for_status()

        # Extract client UUID from Location header
        client_uuid = resp.headers.get("Location", "").split("/")[-1]
        if not client_uuid:
            # Fallback: query again
            resp = requests.get(
                f"{base_url}/admin/realms/{realm}/clients",
                headers={"Authorization": f"Bearer {token}"},
            )
            resp.raise_for_status()
            match = [c for c in resp.json() if c["clientId"] == CLIENT_ID]
            client_uuid = match[0]["id"]

    # Keycloak 26 ignores POST body and always generates a random secret.
    # POST to /client-secret regenerates the secret, then we read it back.
    resp = requests.post(
        f"{base_url}/admin/realms/{realm}/clients/{client_uuid}/client-secret",
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
        },
    )
    resp.raise_for_status()
    secret_value = resp.json().get("value", "")
    _actual_client_secret = secret_value
    print(f"    ✓ Client {CLIENT_ID} in {realm} (secret: {secret_value})")
    return client_uuid


def create_all_clients(base_url: str, token: str) -> dict[str, str]:
    """Create clients in all realms. Returns {realm: client_uuid}."""
    print("[6/8] Creating clients in realms...")
    client_uuids: dict[str, str] = {}

    for realm in REALMS:
        client_uuids[realm] = create_client(base_url, token, realm)
    print()
    return client_uuids


# ------------------------------------------------------------------
# 7. Configure Client (Roles in Access Token)
# ------------------------------------------------------------------


def configure_role_claim(base_url: str, token: str, realm: str, client_uuid: str) -> None:
    """Ensure realm roles are included in the access token.

    Roles are included in the access token by default in Keycloak, but we
    verify a mapper exists to ensure the claim is always emitted.
    """
    print(f"  Configuring role claim for {realm}...")

    # Get existing protocol mappers
    resp = requests.get(
        f"{base_url}/admin/realms/{realm}/clients/{client_uuid}/protocol-mappers/models",
        headers={"Authorization": f"Bearer {token}"},
    )
    resp.raise_for_status()
    mappers = resp.json()
    has_role_mapper = any(
        m["protocolMapper"] == "oidc-usermodel-realm-role-mapper"
        for m in mappers
    )

    if has_role_mapper:
        print("    ⏭ Realm role mapper already exists")
        return

    resp = api_request(
        "POST",
        f"{base_url}/admin/realms/{realm}/clients/{client_uuid}/protocol-mappers/models",
        token,
        {
            "name": "realm-roles",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-usermodel-realm-role-mapper",
            "config": {
                "access.token.claim": "true",
                "userinfo.token.claim": "true",
                "id.token.claim": "false",
                "claim.name": "realm_access.roles",
                "jsonType.label": "String",
                "multivalued": "true",
            },
        },
    )
    resp.raise_for_status()
    print("    ✓ Realm role mapper created")


def configure_all_role_claims(
    base_url: str,
    token: str,
    client_uuids: dict[str, str],
) -> None:
    """Configure role claim for all realms."""
    print("[7/8] Configuring role claim in access token...")

    for realm in REALMS:
        configure_role_claim(base_url, token, realm, client_uuids[realm])
    print()


# ------------------------------------------------------------------
# 8. Summary
# ------------------------------------------------------------------


def _find_env_file() -> str | None:
    """Find the docker .env file.

    Searches:
    1. Same directory as this script
    2. Parent directory (project root .env)
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(script_dir, ".env"),
        os.path.join(script_dir, "..", ".env"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return os.path.abspath(path)
    return None


def _update_env_file(env_path: str, secret: str) -> None:
    """Update OIDC_CLIENT_SECRET in the .env file in place."""
    try:
        with open(env_path, "r") as f:
            lines = f.readlines()

        new_lines: list[str] = []
        updated = False
        for line in lines:
            if line.startswith("OIDC_CLIENT_SECRET="):
                new_lines.append(f"OIDC_CLIENT_SECRET={secret}\n")
                updated = True
            else:
                new_lines.append(line)

        if not updated:
            # Append if not found
            new_lines.append(f"\n# -- OIDC --\nOIDC_CLIENT_SECRET={secret}\n")

        with open(env_path, "w") as f:
            f.writelines(new_lines)

        print(f"  ✓ Updated OIDC_CLIENT_SECRET in {env_path}")
    except OSError as e:
        print(f"  ⚠ Failed to update {env_path}: {e}")


def update_oidc_configs(actual_secret: str) -> None:
    """Print and automatically update the Keycloak client secret in .env files.

    The oauth2-proxy is configured via environment variables. After generating
    a new client secret, this function writes it to the .env file(s) so the
    caller does not have to update them manually.
    """
    print(f"  ✓ Client secret: {actual_secret}")

    # Auto-update .env files
    env_path = _find_env_file()
    if env_path:
        _update_env_file(env_path, actual_secret)
    else:
        print("  ⚠ No .env file found. Set OIDC_PROXY_CLIENT_SECRET manually.")


def print_summary(base_url: str, admin_user: str, admin_pass: str, actual_secret: str) -> None:
    """Print a summary of the setup."""
    print("=== Setup Complete ===")
    print()
    print(f"Realms created: {', '.join(REALMS)}")
    print()
    print("Roles created:")
    for role_name, description in ROLES.items():
        print(f"  {role_name}: {description}")
    for composite_name, sub_roles in COMPOSITE_ROLES.items():
        print(f"  {composite_name}: (composite of {len(sub_roles)} roles)")
    print()
    print("Users per realm:")
    for username, config in USERS.items():
        role_list = ", ".join(config["roles"])
        print(f"  {username} (password: {config['password']}) → roles: {role_list}")
    print()
    print(f"Client: {CLIENT_ID} (confidential, PKCE enabled)")
    print(f"Client Secret: {actual_secret}")
    print("Redirect URIs:")
    print(f"  Main:     {OIDC_MAIN_REDIRECT_URI}")
    print()
    print(f"Keycloak Admin Console:")
    print(f"  URL: {base_url}/admin")
    print(f"  Login: {admin_user} / {admin_pass}")
    print()
    print("Access Control (Role-Based):")
    print("  - Roles are extracted from access token by oauth2-proxy")
    print("  - X-Forwarded-Groups header contains 'role:<name>' values")
    print("  - Caddy enforces path-level access via header_regexp rules")
    print("  - Role sync service auto-propagates role changes to Caddy")
    print()


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Keycloak Setup for ConciergeOS. "
        "Provisions realms, users, roles, and client configuration."
    )
    # Parse KEYCLOAK_URL to extract host and port
    kc_url = settings.KEYCLOAK_URL.replace("http://", "").replace("/auth", "")
    if ":" in kc_url:
        default_host, default_port = kc_url.rsplit(":", 1)
        try:
            default_port = int(default_port)
        except ValueError:
            default_host = kc_url
            default_port = 8080
    else:
        default_host = kc_url
        default_port = 8080

    parser.add_argument(
        "host",
        nargs="?",
        default=default_host,
        help=f"Keycloak host (default: from KEYCLOAK_URL env var or '{default_host}')",
    )
    parser.add_argument(
        "port",
        nargs="?",
        type=int,
        default=default_port,
        help=f"Keycloak port (default: from KEYCLOAK_URL env var or {default_port})",
    )
    args = parser.parse_args()

    base_url = get_base_url(args.host, args.port)
    admin_user = settings.KEYCLOAK_ADMIN_USER
    admin_pass = settings.KEYCLOAK_ADMIN_PASSWORD

    print("=== Keycloak Setup for ConciergeOS ===")
    print(f"Connecting to: {base_url}")
    print()

    # 1. Authenticate
    token = authenticate(base_url, admin_user, admin_pass)

    # 2. Create realms
    create_realms(base_url, token)

    # 3. Create roles (replaces groups)
    role_data = create_all_roles(base_url, token)

    # 4. Create users
    user_ids = create_all_users(base_url, token)

    # 5. Assign users to roles (replaces group assignment)
    assign_all_users_to_roles(base_url, token, user_ids, role_data)

    # 6. Create clients
    client_uuids = create_all_clients(base_url, token)

    # 7. Configure role claim (replaces groups claim)
    configure_all_role_claims(base_url, token, client_uuids)

    # 7.5 Display client secret for env var configuration
    actual_secret = _actual_client_secret
    print("[7.5/8] Client secret (set OAUTH2_PROXY_CLIENT_SECRET env var)...")
    update_oidc_configs(actual_secret)
    print()

    # 8. Summary
    print_summary(base_url, admin_user, admin_pass, actual_secret)


if __name__ == "__main__":
    main()