provider = "keycloak"
oidc_issuer_url = "http://out-customer.com/auth/realms/production"
client_id = "concierge"
client_secret = "changeme"
redirect_url = "http://out-customer.com/settings/oauth2/callback"
cookie_secret = "WVLqV8UqJ5k9v2x7n4m1b3c6d0f8a2e5"
cookie_secure = false
email_domains = ["*"]
allowed_groups = ["single", "all"]
oidc_groups_claim = "groups"
upstreams = ["http://frontend:80/"]
http_address = "0.0.0.0:4181"
proxy_prefix = "/settings/oauth2"
reverse_proxy = true
scope = "openid profile email"
pass_access_token = false
pass_authorization_header = false
pass_user_headers = true
set_xauthrequest = false
ssl_insecure_skip_verify = true
