provider = "keycloak-oidc"
oidc_issuer_url = "https://out-customer.com/auth/realms/production"
client_id = "concierge"
client_secret = "k8geBhfEysBaZetti9Oiw2ca1YOa13SP"
redirect_url = "https://out-customer.com/settings/oauth2/callback"
cookie_secret = "WVLqV8UqJ5k9v2x7n4m1b3c6d0f8a2e5"
cookie_secure = false
email_domains = ["*"]
allowed_groups = ["single"]
oidc_groups_claim = "groups"
upstreams = ["http://frontend:80/"]
http_address = "0.0.0.0:4181"
proxy_prefix = "/settings/oauth2"
reverse_proxy = true
scope = "openid profile email"
pass_access_token = false
pass_authorization_header = false
pass_user_headers = true
set_xauthrequest = false
ssl_insecure_skip_verify = true
code_challenge_method = "S256"
oidc_extra_audiences = ["account"]
# Force periodic session validation with Keycloak
cookie_refresh = "1m"
cookie_expire = "1h"
